// Purpose: Centralize rollback-host routes that should run through the local parity handler.

export const LOCAL_FALLBACK_MUTATION_PATHS = new Set([
  "/profile/default-warehouse",
  "/admin/member-permissions",
  "/admin/user-permissions",
  "/owner/admin-permissions",
  "/owner/notification-preferences",
  "/owner/warehouses/add",
  "/owner/owner-companies/upsert",
  "/owner/owner-companies/deactivate",
  "/owner/inventory-ownership/box",
  "/owner/inventory-ownership/caulk-stock",
  "/owner/inventory-ownership/bulk-transfer",
  "/owner/caulk/manufacturers/upsert",
  "/box-dealers/upsert",
  "/caulk/products/upsert",
  "/caulk/mutate",
  "/caulk/transfer",
  "/caulk/transfers/receive",
  "/caulk/transfers/cancel",
  "/boxes/add",
  "/boxes/delete",
  "/boxes/update",
  "/boxes/receive",
  "/boxes/labels/mark-printed",
  "/boxes/set-status",
  "/boxes/transfer/start",
  "/boxes/transfer/receive",
  "/boxes/transfer/cancel",
  "/allocations/apply",
  "/allocations/remove-box",
  "/allocations/planner-suppression/clear",
  "/allocations/caulk/add",
  "/allocations/caulk/update",
  "/allocations/caulk/checkout",
  "/allocations/caulk/checkin",
  "/allocations/caulk/remove",
  "/jobs/create",
  "/jobs/update",
  "/jobs/requirement-state",
  "/jobs/set-staged-pickup",
  "/jobs/checkout-all",
  "/jobs/complete",
  "/jobs/delete",
  "/jobs/reopen",
  "/film-orders/create",
  "/film-orders/cancel",
  "/film-orders/delete",
  "/film-orders/manual-fulfill",
  "/film-weight/pending-reviews/resolve",
  "/audit/undo",
]);

export const LOCAL_FALLBACK_READ_PATHS = new Set([
  "/app/attention-summary",
  "/warehouses/list",
  "/boxes/search",
  "/boxes/suggest-next-id",
  "/boxes/get",
  "/boxes/transfer/by-box",
  "/boxes/transfer/plan",
  "/owner-companies/list",
  "/audit/list",
  "/audit/by-box",
  "/caulk/manufacturers/list",
  "/box-dealers/list",
  "/caulk/products/list",
  "/caulk/stock/list",
  "/allocations/by-box",
  "/allocations/by-job",
  "/allocations/jobs",
  "/allocations/preview",
  "/film-orders/list",
  "/film-orders/get",
  "/film-data/catalog",
  "/film-weight/profiles",
  "/film-weight/pending-reviews",
  "/owner/reports/asset-total-cost",
  "/reports/summary",
  "/jobs/calendar",
  "/jobs/check-duplicate",
  "/jobs/get",
  "/jobs/get-by-id",
  "/jobs/list",
  "/jobs/search",
  "/caulk/transactions/list",
  "/caulk/transfers/list",
  "/roll-history/by-box",
  "/auth/context",
  "/admin/access/requests",
  "/admin/feature-permissions",
  "/admin/username-requests",
]);

export function shouldUseLocalFallbackRoute(method, logicalPath) {
  return (
    (method === "GET" && LOCAL_FALLBACK_READ_PATHS.has(logicalPath)) ||
    (method === "POST" && LOCAL_FALLBACK_MUTATION_PATHS.has(logicalPath))
  );
}
